**Linear Regression with multiple regression or Multivariate Regression**

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("./data/homeprices2.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [3]:
# handling nan values>>

import math
df.bedrooms.median()

4.0

In [5]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())

In [6]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
model = linear_model.LinearRegression()
model.fit(df.drop('price', axis='columns') ,df.price) # to train the model

LinearRegression()

In [8]:
# Testing the model
#prediction

In [11]:
# the house with the area of 3000, 3 bedrooms and 40 years age of the house

In [14]:
model.predict([[3000, 3, 40]])

/home/kashiii/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [15]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [16]:
model.intercept_

221323.00186540408

In [18]:
112.06244194*3000+23388.88007794*3-3231.71790863*40 + 221323.00186540408

498408.2515740241

In [19]:
# second test

# the house with the area of 2500, 4 bedrooms and 5 years age of the house

In [20]:
model.predict([[2500, 4, 5]])

/home/kashiii/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

## Exercise

In [12]:
!pip install word2number

  Preparing metadata (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5566 sha256=ece804f7a4856e74e66f5e265f91989e0f2a8cc06b340ebf8763ac86c3fe2551
  Stored in directory: /home/kashiii/.cache/pip/wheels/cd/ef/ae/073b491b14d25e2efafcffca9e16b2ee6d114ec5c643ba4f06
Successfully built word2number


In [13]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [2]:
df = pd.read_csv("./data/hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [4]:
df["test_score(out of 10)"] = df["test_score(out of 10)"].fillna(df["test_score(out of 10)"].median())

In [5]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [14]:
df.experience = df.experience.fillna("zero")

In [15]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [16]:
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [17]:
model = linear_model.LinearRegression()
model.fit(df.drop("salary($)", axis="columns") ,df["salary($)"])

LinearRegression()

In [18]:
# Now predict the model
# 2yr of experience, test score 9 outoff 10 and interview score is 6 outoff 10

In [21]:
model.predict([[2, 9, 6]])

/home/kashiii/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [22]:
#  12yr of experience, test score 10 outoff 10 and interview score is 6 outoff 10

model.predict([[12,10,10]])

/home/kashiii/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])