In [55]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
from sklearn.datasets import load_digits
digits = load_digits()

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [10]:
lr = LogisticRegression()
lr.fit(X_train, y_train)

/home/kashiii/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [11]:
lr.score(X_test, y_test)

0.9574074074074074

In [12]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9888888888888889

In [13]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9796296296296296

In [14]:
# if we will run the above train test split cell again and again we will have different score. Suppose if 
# we will run the 10 times and than calculate the average of all the scores this is what K fold does

In [15]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)

In [16]:
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [18]:
for train_index, test_index in kf.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
    print(train_index, test_index)
    
# in the output the above is creating 3 folds and 2 is using for training and one for testing and repeats this for 3 times

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [19]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [22]:
get_score(LogisticRegression(), X_train, X_test, y_train, y_test)  # try SVC, and RandomForestClassifier

/home/kashiii/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9574074074074074

In [31]:
from sklearn.model_selection import StratifiedKFold    # stratifiedKFold will divide the data in uniform
folds = StratifiedKFold(n_splits=3)

score_logistic = []
score_svm = []
score_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    X_tran, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                      digits.target[train_index], digits.target[test_index]
    
    score_logistic.append(get_score(LogisticRegression(), X_tran, X_test, y_train, y_test))
    score_svm.append(get_score(SVC(), X_tran, X_test, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_tran, X_test, y_train, y_test))
    

/home/kashiii/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/kashiii/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-

In [32]:
score_logistic

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [33]:
score_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [35]:
score_rf

[0.9265442404006677, 0.9432387312186978, 0.9131886477462438]

In [36]:
# sklearn library function that will do the above all we don't need to write the code by ourselves

In [37]:
from sklearn.model_selection import cross_val_score

In [38]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

/home/kashiii/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/kashiii/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [39]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [43]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target) # try cv=3 parameter the by default value is 5

array([0.92777778, 0.90555556, 0.95543175, 0.9637883 , 0.9275766 ])

In [47]:
scores_rf = cross_val_score(RandomForestClassifier(n_estimators=5), digits.data, digits.target, cv=10)  # try increasing no of trees
np.average(scores_rf)

0.8781471135940409

In [45]:
scores_svm = cross_val_score(SVC(), digits.data, digits.target, cv=10)
np.average(scores_svm)

0.9699503414028554

In [46]:
scores_logistic = cross_val_score(LogisticRegression(), digits.data, digits.target, cv=10)
np.average(scores_logistic)

/home/kashiii/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/kashiii/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-

0.928193668528864

# Exercise

In [92]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [93]:
iris = load_iris()

In [94]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

**Logistic Regression**

In [95]:
l_scores = cross_val_score(LogisticRegression(), iris.data, iris.target)
l_scores

/home/kashiii/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [96]:
np.average(l_scores)

0.9733333333333334

**Support Vector Machine (SVM)**

In [97]:
s_scores = cross_val_score(SVC(), iris.data, iris.target)
s_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [98]:
np.average(s_scores)

0.9666666666666666

**Random Forest**

In [99]:
r_scores = cross_val_score(RandomForestClassifier(), iris.data, iris.target)  # try increasing no of trees
r_scores

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [100]:
np.average(r_scores)

0.96

**Decision Tree**

In [101]:
d_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
d_scores

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [102]:
np.average(d_scores)

0.9600000000000002

In [103]:
# in our case the logistic regression is best it has highest score